version: '3'

services:
  usdz-api:
    image: eboraas/laravel
    container_name: usdz-api-${ENV}
    volumes:
      - ./usdz-api:/var/www/laravel
    working_dir: /var/www/laravel
    ports:
      - ${USDZ_API_PORT}:80
    stdin_open: true
    tty: true

